# Use OpenJDK as the base image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the dodgygeezer JAR file into the container
COPY target/dodgygeezers-3.4.3.jar /app/dodgygeezers.jar

# Expose the internal port (not exposed to the host machine)
EXPOSE 8082

# Command to run the dodgygeezer service
ENTRYPOINT ["java", "-jar", "dodgygeezers.jar"]
